/**
 * Root project file templates.
 */

export const rootPackageJsonTemplate = `{
  "name": "{{projectName}}",
  "version": "1.0.0",
  "description": "{{projectName}} — SAP BTP application (CAP + SAPUI5 + AppRouter)",
  "private": true,
  "workspaces": [
    "approuter",
    "srv"
  ],
  "scripts": {
    "start:local": "cd srv && npm run watch",
    "build": "mbt build",
    "lint": "echo 'No root lint configured'",
    "test": "cd srv && npm test"
  },
  "devDependencies": {
    "mbt": "^1.2.0"
  },
  "engines": {
    "node": ">=18"
  }
}`;

export const projectReadmeTemplate = `# {{projectName}}

SAP BTP application — CAP backend + SAPUI5 frontend + AppRouter.

Generated by [btp-starter-pack](https://github.com/your-org/btp-starter-pack).

---

## Architecture

\`\`\`
User Browser
    │
    ▼
AppRouter (approuter/)          ← XSUAA auth, routing
    │
    ├──→ SAPUI5 App (app/{{projectName}}/)   ← HTML5 App Repository
    │
    └──→ CAP Service (srv/)                ← OData V4, Node.js
              │
              └──→ SAP HANA / SQLite
\`\`\`

---

## Prerequisites

| Tool | Version | Install |
|------|---------|---------|
| Node.js | 18+ LTS | https://nodejs.org |
| @sap/cds-dk | 7+ | \`npm i -g @sap/cds-dk\` |
| CF CLI | 8+ | https://github.com/cloudfoundry/cli |
| MBT | 1.2+ | \`npm i -g mbt\` |

---

## Local Development

\`\`\`bash
# Install dependencies
npm install
cd srv && npm install && cd ..

# Start CAP with mock auth (SQLite in-memory)
cd srv && cds watch
\`\`\`

Open [http://localhost:4004](http://localhost:4004)

---

## Deploy to SAP BTP Cloud Foundry

### 1. Login

\`\`\`bash
btp login
cf login -a https://api.cf.{{btpRegion}}.hana.ondemand.com --sso
\`\`\`

### 2. Build MTA

\`\`\`bash
mbt build
\`\`\`

### 3. Deploy

\`\`\`bash
cf deploy mta_archives/{{projectName}}_1.0.0.mtar
\`\`\`

---

## BTP Services Required

| Service | Plan | Instance Name |
|---------|------|---------------|
| xsuaa | application | {{xsuaaInstance}} |
| destination | lite | {{destinationInstance}} |
| html5-apps-repo | app-host | {{html5RepoInstance}} |

Create them:
\`\`\`bash
btp-starter-pack setup
\`\`\`

Or manually:
\`\`\`bash
cf create-service xsuaa application {{xsuaaInstance}} -c xs-security.json
cf create-service destination lite {{destinationInstance}}
cf create-service html5-apps-repo app-host {{html5RepoInstance}}
\`\`\`

---

## Destinations (Manual — SAP BTP Cockpit)

Configure in BTP Cockpit → Subaccount → Connectivity → Destinations:

- \`S4HANA\` — see \`destinations/s4hana-destination.json\` for template
- \`EXTERNAL_API\` — see \`destinations/api-external-destination.json\` for template

---

## Role Collections (Manual — SAP BTP Cockpit)

After deployment, assign role collections in Cockpit:

1. Cockpit → Subaccount → Security → Role Collections
2. Assign \`{{projectName}}-Editor\` or \`{{projectName}}-Viewer\` to your user

---

## Troubleshooting

| Problem | Solution |
|---------|----------|
| \`cf deploy\` fails — service not found | Run \`btp-starter-pack setup\` or create services manually |
| XSUAA 401 Unauthorized | Check role collection assignment in Cockpit |
| UI not loading | Verify HTML5 App Repository binding in AppRouter |
| CAP service returns 403 | Check \`xs-security.json\` scopes and role templates |
| S/4HANA destination fails | Verify destination config and Cloud Connector (if on-premise) |

---

Generated: {{year}} | Region: {{btpRegion}}
`;
