/**
 * clean command — safe cleanup of locally generated files.
 *
 * Security:
 * - NEVER deletes BTP resources without explicit confirmation.
 * - Dry-run is ALWAYS the default first step.
 * - Destructive actions require typing a confirmation phrase.
 * - Only removes local files generated by this tool — never touches BTP cloud resources.
 */

import { Command } from 'commander';
import chalk from 'chalk';
import path from 'path';
import fs from 'fs-extra';
import { logger } from '../core/logger';
import { confirmDestructive } from '../core/prompts';
import { CONFIG_FILENAME } from '../core/config';

interface CleanTarget {
  path: string;
  description: string;
  safe: boolean; // true = definitely safe to delete; false = warn user
}

export function cleanCommand(): Command {
  const cmd = new Command('clean');
  cmd
    .description('Safely remove locally generated files (NEVER deletes BTP cloud resources)')
    .option('--workspace <dir>', 'Workspace directory', '.')
    .option('--include-config', 'Also remove the .btp-starter.json config file (default: NO)')
    .option('--include-logs', 'Also remove the logs/ directory (default: NO)')
    .option('--dry-run', 'Show what would be deleted without deleting anything (default behavior)')
    .action(async (options: {
      workspace: string;
      includeConfig?: boolean;
      includeLogs?: boolean;
      dryRun?: boolean;
    }) => {
      logger.section('btp-starter-pack clean');

      // dry-run is the DEFAULT behavior for clean
      // The user must explicitly pass --no-dry-run to actually delete
      const dryRun = options.dryRun !== false;

      const workspaceDir = path.resolve(options.workspace);

      // ── Build list of targets ─────────────────────────────────────────────────
      const targets: CleanTarget[] = [];

      // Logs directory
      if (options.includeLogs) {
        const logsDir = path.join(workspaceDir, 'logs');
        if (fs.existsSync(logsDir)) {
          targets.push({
            path: logsDir,
            description: 'Logs directory (logs/)',
            safe: true,
          });
        }
      }

      // Config file (only if explicitly requested)
      if (options.includeConfig) {
        const configPath = path.join(workspaceDir, CONFIG_FILENAME);
        if (fs.existsSync(configPath)) {
          targets.push({
            path: configPath,
            description: `Config file (${CONFIG_FILENAME}) — workspace settings will be lost`,
            safe: false, // warn on this one
          });
        }
      }

      // xs-security.json (generated by setup)
      const xsSecPath = path.join(workspaceDir, 'xs-security.json');
      if (fs.existsSync(xsSecPath)) {
        targets.push({
          path: xsSecPath,
          description: 'xs-security.json (generated by setup)',
          safe: true,
        });
      }

      if (targets.length === 0) {
        logger.info('Nothing to clean in this workspace.');
        return;
      }

      // ── Show what would be deleted ─────────────────────────────────────────────
      logger.blank();
      console.log(chalk.bold.cyan('── Files to remove '));
      logger.blank();

      for (const target of targets) {
        const icon = target.safe ? chalk.yellow('⚠') : chalk.red('✖');
        console.log(`  ${icon} ${target.description}`);
        console.log(chalk.gray(`      ${target.path}`));
      }

      logger.blank();
      console.log(chalk.red.bold('⛔  NOTE: This tool NEVER deletes BTP cloud resources.'));
      console.log(chalk.gray('    To delete CF services, use: cf delete-service <name>'));
      console.log(chalk.gray('    To delete CF apps, use:     cf delete <name>'));
      logger.blank();

      if (dryRun) {
        logger.info(chalk.yellow('[dry-run] The above files WOULD be deleted.'));
        logger.info('Run with --no-dry-run to actually delete them.');
        return;
      }

      // ── Real deletion — requires explicit confirmation ─────────────────────────
      const unsafeTargets = targets.filter((t) => !t.safe);
      const phrase = unsafeTargets.length > 0 ? 'confirmo eliminar configuracion' : 'confirmo eliminar';

      const confirmed = await confirmDestructive(
        `Delete ${targets.length} file(s)/director(ies) listed above`,
        phrase
      );

      if (!confirmed) {
        logger.info('Clean cancelled. No files deleted.');
        return;
      }

      // ── Execute deletion ──────────────────────────────────────────────────────
      let deleted = 0;
      let errors = 0;

      for (const target of targets) {
        try {
          if (fs.lstatSync(target.path).isDirectory()) {
            fs.removeSync(target.path);
          } else {
            fs.unlinkSync(target.path);
          }
          logger.success(`Deleted: ${target.path}`);
          deleted++;
        } catch {
          // CWE-209: Generic error message
          logger.error(`Failed to delete: ${path.basename(target.path)}`);
          errors++;
        }
      }

      logger.blank();
      if (errors === 0) {
        logger.success(`Clean complete. ${deleted} item(s) removed.`);
      } else {
        logger.warn(`Clean complete with ${errors} error(s). ${deleted} item(s) removed.`);
      }
    });

  return cmd;
}
